apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: connect-sink-client
  labels:
    strimzi.io/cluster: broker
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: hello-connect
      operations:
        - Describe
        - Read
    - resource:
        type: group
        name: connect-echo-sink
      operations:
       - Read