apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    id: kafka
    realm: kafka
    displayName: "Kafka Realm"
    enabled: true
    sslRequired: none
    roles:
      realm:
        - name: sr-admin
        - name: sr-developer
        - name: sr-readonly

    clients:
      # Kafka broker
      - clientId: kafka-client
        clientAuthenticatorType: client-secret
        secret: kafka-secret
        standardFlowEnabled: false
        serviceAccountsEnabled: true
      # Apicurio Registry instance
      - clientId: registry-client-api
        clientAuthenticatorType: client-secret
        secret: api-secret
        standardFlowEnabled: false
        serviceAccountsEnabled: true
      - clientId: registry-client-ui
        implicitFlowEnabled: true
        redirectUris:
          - '*'
        standardFlowEnabled: true
        webOrigins:
          - '*'
        publicClient: true
      # Quarkus application
      - clientId: quarkus-app-client
        clientAuthenticatorType: client-secret
        secret: quarkus-secret
        standardFlowEnabled: false
        serviceAccountsEnabled: true


    users:
      # Apicurio Registry UI users
      - credentials:
          - temporary: false
            type: password
            value: admin
        enabled: true
        realmRoles:
          - sr-admin
        username: registry-admin
      - credentials:
          - temporary: false
            type: password
            value: developer
        enabled: true
        realmRoles:
          - sr-developer
        username: registry-developer
      - credentials:
          - temporary: false
            type: password
            value: user
        enabled: true
        realmRoles:
          - sr-readonly
        username: registry-user
