apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: echo-sink
  labels:
    strimzi.io/cluster: oauth-connect
spec:
  class: EchoSink
  tasksMax: 1
  config:
    level: INFO
    topics: hello-connect