apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: hello-connect
  labels:
    strimzi.io/cluster: broker
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 107374182